---
creation_rules:
  - path_regex: secrets/.*\.sops\.ya?ml
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age19m4kqg9djjxy6zz025jc858kze09v9w2y4w37jsdf8vry4quq55qe976yz"

stores:
  yaml:
    indent: 2
